/**
 * svg 文件和 className 的对应关系
 */
module.exports = {
    BarsOutlined: 'anticon-bars',
    CalendarOutlined: 'anticon-calendar',
    CaretDownFilled: 'anticon-caret-down',
    CaretRightFilled: 'anticon-caret-right',
    CaretUpFilled: 'anticon-caret-up',
    CheckCircleFilled: 'dt-anticon-check-circle-fill',
    // CheckCircleFilled: 'anticon-check-circle',
    CheckCircleOutlined: 'anticon-check-circle',
    CheckOutlined: 'anticon-check',
    ClockCircleOutlined: 'anticon-clock-circle',
    CloseCircleFilled: 'anticon-close-circle',
    CloseOutlined: 'anticon-close',
    DeleteOutlined: 'anticon-delete',
    DoubleLeftOutlined: 'anticon-double-left',
    DoubleRightOutlined: 'anticon-double-right',
    DownOutlined: 'anticon-down',
    DownloadOutlined: 'anticon-download',
    DragOutlined: 'anticon-drag',
    EditOutlined: 'anticon-edit',
    EllipsisOutlined: 'anticon-ellipsis',
    ExclamationCircleFilled: 'dt-anticon-exclamation-circle-fill',
    // ExclamationCircleFilled: 'anticon-exclamation-circle',
    ExclamationCircleOutlined: 'anticon-exclamation-circle',
    ExportOutlined: 'anticon-export',
    EyeInvisibleOutlined: 'anticon-eye-invisible',
    EyeOutlined: 'anticon-eye',
    FilterFilled: 'anticon-filter',
    HomeOutlined: 'anticon-home',
    ImportOutlined: 'anticon-import',
    LayoutOutlined: 'anticon-layout',
    LeftOutlined: 'anticon-left',
    MenuFoldOutlined: 'anticon-menu-fold',
    MenuUnfoldOutlined: 'anticon-menu-unfold',
    MessageOutlined: 'anticon-message',
    MinusCircleOutlined: 'anticon-minus-circle',
    MinusSquareOutlined: 'anticon-minus-square',
    MoreOutlined: 'anticon-more',
    PaperClipOutlined: 'anticon-paper-clip',
    PlusCircleOutlined: 'anticon-plus-circle',
    PlusOutlined: 'anticon-plus',
    PlusSquareOutlined: 'anticon-plus-square',
    QuestionCircleOutlined: 'anticon-question-circle',
    ReloadOutlined: 'anticon-reload',
    RightOutlined: 'anticon-right',
    SearchOutlined: 'anticon-search',
    SettingOutlined: 'anticon-setting',
    StarOutlined: 'anticon-star',
    SwapOutlined: 'anticon-swap',
    SwapRightOutlined: 'anticon-swap-right',
    UpOutlined: 'anticon-up',
    UploadOutlined: 'anticon-upload',
    UserOutlined: 'anticon-user',
    WarningFilled: 'anticon-warning',
    ZoomInOutlined: 'anticon-zoom-in',
    ZoomOutOutlined: 'anticon-zoom-out',
};
